# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Kewei Ni
author_email: bhklab.farnooshabbas-aghababazadeh@gmail.com
author_full_name: Farnoosh Abbas-Aghababazadeh
github_username: RibaA
has_additional_authors: true
project_description: 'Feature selection to find an optimal subset of features '
project_name: Conformal Floating Feature Selection
project_slug: conformal-ffs
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
